-- MySQL Script generated by MySQL Workbench
-- Sat Feb 22 21:32:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_ID` INT NOT NULL,
  `p_name` VARCHAR(255) NOT NULL,
  `p_price` DECIMAL(10,2) NOT NULL,
  `p_info` TEXT NULL,
  `p_delivery_available` TINYINT NOT NULL,
  PRIMARY KEY (`product_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_ID` INT NOT NULL,
  `c_name` VARCHAR(255) NOT NULL,
  `c_address` VARCHAR(255) NOT NULL,
  `c_phone` VARCHAR(20) NOT NULL,
  `c_contact_person` VARCHAR(100) NOT NULL,
  `customerscol` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_ID` INT NOT NULL,
  `order_customer_ID` INT NOT NULL,
  `order_product_ID` INT NOT NULL,
  `order_quantity` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`order_ID`),
  INDEX `customer_ID_idx` (`order_customer_ID` ASC) VISIBLE,
  INDEX `product_ID_idx` (`order_product_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`order_customer_ID`)
    REFERENCES `mydb`.`customers` (`customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_ID`
    FOREIGN KEY (`order_product_ID`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery_types` (
  `delivery_type_ID` INT NOT NULL,
  `dt_name` VARCHAR(100) NOT NULL,
  `dt_price` DECIMAL(10,2) NOT NULL,
  `dt_speed` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`delivery_type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deliveries` (
  `deliveries` INT NOT NULL,
  `delivery_order_ID` INT NOT NULL,
  `delivery_type_ID` INT NULL,
  `delivery_cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`deliveries`),
  INDEX `order_ID_idx` (`delivery_order_ID` ASC) VISIBLE,
  INDEX `delivery_type_ID_idx` (`delivery_type_ID` ASC) VISIBLE,
  CONSTRAINT `order_ID`
    FOREIGN KEY (`delivery_order_ID`)
    REFERENCES `mydb`.`orders` (`order_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `delivery_type_ID`
    FOREIGN KEY (`delivery_type_ID`)
    REFERENCES `mydb`.`delivery_types` (`delivery_type_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_delivery_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_delivery_types` (
  `product_ID` INT NOT NULL,
  `delivery_type_ID` INT NOT NULL,
  INDEX `product_ID_idx` (`product_ID` ASC) VISIBLE,
  INDEX `delivery_type_ID_idx` (`delivery_type_ID` ASC) VISIBLE,
  CONSTRAINT `product_ID`
    FOREIGN KEY (`product_ID`)
    REFERENCES `mydb`.`products` (`product_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `delivery_type_ID`
    FOREIGN KEY (`delivery_type_ID`)
    REFERENCES `mydb`.`delivery_types` (`delivery_type_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
